back/api/urls.py
from django.urls import path, include
from .views import HomeView


app_name = 'api'


urlpatterns = [

    path('', HomeView.as_view(), name="home"),

]

back/back/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('api.urls')),

]

back/api/models.py
from django.db import models

# Create your models here.

back/api/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.http import HttpResponseRedirect

import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
import numpy as np


import joblib

class HomeView(View):
    template = 'home.html'

    def get(self, request):
        df = joblib.load('static/selected_df.pkl')
        selected_cols = df.columns
        disease = joblib.load('static/disease.pkl').unique()[:3]
        dict = []
        numerics = df.select_dtypes('number').columns

        for sel in selected_cols:
            if sel not in numerics:
                values = df[sel].unique()
                dict.append([sel, values])
            else:
                dict.append([sel])

        context = {'sel': dict,
                   'dis': disease,
                   'predict': False}
        return render(request, self.template, context)

    def post(self, request):
        df = joblib.load('static/selected_df.pkl')
        model = joblib.load('static/model.pkl')
        disease = joblib.load('static/disease.pkl').unique()

        selected_cols = df.columns

        lst = []
        for sel in selected_cols:
            lst.append(request.POST.get(sel))

        varlst = []
        numerics = df.select_dtypes('number').columns
        for sel, var in zip(selected_cols, lst):

            if sel not in numerics:
                vars = sorted(df[sel].unique())
                index = vars.index(var)
                varlst.append(index)
            else:
                varlst.append(var)

        nplist = np.array(varlst).reshape(1, -1)

        result = model.predict_proba(nplist).tolist()[0]

        resultVars = []
        for disease, result in zip(disease, result):
            resultVars.append([disease, round(result*100, 0)])
        resultVars = sorted(resultVars, key=lambda l: l[1], reverse=True)[:3]


        dict = []
        numerics = df.select_dtypes('number').columns

        for sel in selected_cols:
            if sel not in numerics:
                values = df[sel].unique()
                dict.append([sel, values])
            else:
                dict.append([sel])

        context = {'sel': dict,
                   'dis': resultVars,
                   'predict': True}

        return render(request, self.template, context)

back/api/templates/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Disease Prediction</title>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'tem.png' %}">

    <link rel="stylesheet" href="{% static 'home.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">

</head>
<body>

<div class="newsletter-subscribe">
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col col-lg-6">
                <div class="intro">
                    <h2 class="text-center">I am helping physicians with their diagnosis by using machine learning</h2>
                    <p class="text-center">Please provide as many features as possible on the right, and click the
                        predict button. </p>
                </div>

                <div class="intro box">
                    <h3 class="text-center">I would suggest you to consider diseases below based on their probabilities
                        attached.</h3>
                    {% if predict %}
                    <h5 >1. {{ dis.0.0 }} {{ dis.0.1 }}%</h5>

                    <h5 >2. {{ dis.1.0 }} {{ dis.1.1 }}%</h5>

                    <h5 >3. {{ dis.2.0 }} {{ dis.2.1 }}%</h5>


                    {% endif %}

                </div>
            </div>
            <div class="col col-lg-6 box">

                <form method="post" id="predict_form" action="{% url 'api:home' %}">
                    {% csrf_token %}
                    <div class="card-body">

                        {% for sel in sel %}
                        {% if sel|length == 2 %}
                        <div class="form-group">
                            <label>{{ sel.0 }}</label>
                            <select class="form-control" name="{{ sel.0 }}">
                                {% for del in sel.1 %}
                                <option value="{{ del }}">{{ del }}</option>
                                {% endfor %}
                            </select>

                        </div>
                        {% else %}
                        <div class="form-group">
                            <label>{{ sel.0 }}</label>
                            <input type="number" class="form-control" value="0" name="{{ sel.0 }}">
                        </div>
                        {% endif %}

                        {% endfor %}
                    </div>


                    <button id="predict" type="submit" class="btn btn-primary">Predict</button>
                    <a href="{% url 'api:home' %}" id="clear" class="btn btn-warning">Clear</a>
                </form>

            </div>

        </div>
    </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>


</body>
</html>